ARG cvmfsversion=2.9.4
ARG fuseoverlayfsversion=1.9

FROM ubuntu:20.04
ARG cvmfsversion
ARG fuseoverlayfsversion

RUN apt-get update
RUN apt-get install -y sudo wget kitty-terminfo vim openssh-client gawk autofs curl attr uuid fuse3 libfuse2 psmisc gdb uuid-dev lsof

RUN cd /root && wget http://mirrors.ccr.buffalo.edu/ccr/cvmfs/cvmfs-config-ccr-latest.all.deb \
    && wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-config/cvmfs-config-default_latest_all.deb \
    && wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-${cvmfsversion}/cvmfs_${cvmfsversion}~1+ubuntu20.04_$(dpkg --print-architecture).deb \
    && wget https://ecsft.cern.ch/dist/cvmfs/cvmfs-${cvmfsversion}/cvmfs-fuse3_${cvmfsversion}~1+ubuntu20.04_$(dpkg --print-architecture).deb

RUN dpkg -i /root/cvmfs_${cvmfsversion}~1+ubuntu20.04_$(dpkg --print-architecture).deb \
            /root/cvmfs-fuse3_${cvmfsversion}~1+ubuntu20.04_$(dpkg --print-architecture).deb \
            /root/cvmfs-config-default_latest_all.deb \
            /root/cvmfs-config-ccr-latest.all.deb

RUN curl -L -o /usr/local/bin/fuse-overlayfs https://github.com/containers/fuse-overlayfs/releases/download/v${fuseoverlayfsversion}/fuse-overlayfs-$(uname -m) \
  && chmod +x /usr/local/bin/fuse-overlayfs

RUN echo 'CVMFS_QUOTA_LIMIT=10000' > /etc/cvmfs/default.local \
  && echo 'CVMFS_CLIENT_PROFILE="single"' >> /etc/cvmfs/default.local

RUN mkdir -p /cvmfs/soft.ccr.buffalo.edu
